---
name: "Recoreon"

options:
  bundleIdPrefix: com.github.umireon
  deploymentTarget:
    iOS: "16.0"

settings:
  CODE_SIGN_STYLE: "Automatic"
  DEVELOPMENT_TEAM: "4HMJS6J4MZ"
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1

packages:
  FFmpegKit:
    url: "https://github.com/kaito-tokyo/ffmpeg-kit-spm.git"
    from: "6.0.3"

targets:
  RecoreonCommon:
    type: "library.static"
    platform: "iOS"
    sources:
      - "RecoreonCommon"

  RecoreonBroadcastUploadExtension:
    type: "app-extension"
    platform: "iOS"
    sources:
      - "RecoreonBroadcastUploadExtension"
    dependencies:
      - target: "RecoreonCommon"
      - package: "FFmpegKit"
    settings:
      SWIFT_OBJC_BRIDGING_HEADER: "RecoreonBroadcastUploadExtension/RecoreonBroadcastUploadExtension-Bridging-Header.h"
    info:
      path: "RecoreonBroadcastUploadExtension/Info.plist"
      properties:
        CFBundleDisplayName: "Recoreon"
        CFBundleIdentifier: "com.github.umireon.Recoreon.RecoreonBroadcastUploadExtension"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSCameraUsageDescription: "This app do not use a camera."
        NSExtension:
          NSExtensionPointIdentifier: "com.apple.broadcast-services-upload"
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).SampleHandler"
          RPBroadcastProcessMode: "RPBroadcastProcessModeSampleBuffer"
    entitlements:
      path: "RecoreonBroadcastUploadExtension/RecoreonBroadcastUploadExtension.entitlements"
      properties:
        com.apple.security.application-groups:
          - "group.com.github.umireon.Recoreon"

  Recoreon:
    type: "application"
    platform: "iOS"
    sources:
      - "Recoreon"
    settings:
      DEVELOPMENT_ASSET_PATHS: '"Recoreon/Preview Content"'
    dependencies:
      - package: "FFmpegKit"
      - target: "RecoreonCommon"
      - target: "RecoreonBroadcastUploadExtension"
    info:
      path: "Recoreon/Info.plist"
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        ITSAppUsesNonExemptEncryption: false
        LSRequiresIPhoneOS: true
        NSCameraUsageDescription: "This app do not use a camera."
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations~ipad:
          - "UIInterfaceOrientationPortrait"
          - "UIInterfaceOrientationPortraitUpsideDown"
          - "UIInterfaceOrientationLandscapeLeft"
          - "UIInterfaceOrientationLandscapeRight"
        UISupportedInterfaceOrientations~iphone:
          - "UIInterfaceOrientationPortrait"
          - "UIInterfaceOrientationLandscapeLeft"
          - "UIInterfaceOrientationLandscapeRight"
    entitlements:
      path: "Recoreon/Recoreon.entitlements"
      properties:
        com.apple.security.application-groups:
          - "group.com.github.umireon.Recoreon"