---
name: "Recoreon"

options:
  bundleIdPrefix: com.github.umireon
  deploymentTarget:
    iOS: "17.4"

fileGroups:
  - "PrivacyInfo.xcprivacy"
  - "RecoreonTests.xctestplan"
  - "RecoreonUITests.xctestplan"
  - "FragmentedRecordWriterTests.xctestplan"

settings:
  # Signing settings
  CODE_SIGN_STYLE: "Automatic"
  DEVELOPMENT_TEAM: "4HMJS6J4MZ"

  # Versioning settings
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1

  # Objective-C settings
  CLANG_ENABLE_MODULES: true

  # Warnings settings
  CLANG_WARN_DOCUMENTATION_COMMENTS: false
  CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: false

packages:
  FFmpegKit:
    url: "https://github.com/kaito-tokyo/ffmpeg-kit-spm.git"
    from: "6.0.3"

targets:
  FragmentedRecordWriter:
    type: "library.static"
    platform: "iOS"
    sources:
      - "FragmentedRecordWriter"
    settings:
      SWIFT_OBJC_BRIDGING_HEADER: "FragmentedScreenRecordWriter/FragmentedScreenRecordWriter-Bridging-Header.h"

  FragmentedScreenRecordWriterTests:
    type: "bundle.unit-test"
    platform: "iOS"
    sources:
      - "FragmentedRecordWriterTests"
    dependencies:
      - target: "FragmentedRecordWriter"
    settings:
      SWIFT_OBJC_BRIDGING_HEADER: "FragmentedRecordWriterTests/FragmentedRecordWriterTests-Bridging-Header.h"

  ScreenRecordWriter:
    type: "library.static"
    platform: "iOS"
    sources:
      - "ScreenRecordWriter"
    dependencies:
      - package: "FFmpegKit"

  RecoreonCommon:
    type: "library.static"
    platform: "iOS"
    sources:
      - "RecoreonCommon"

  RecoreonBroadcastUploadExtension:
    type: "app-extension"
    platform: "iOS"
    sources:
      - "RecoreonBroadcastUploadExtension"
    dependencies:
      - target: "FragmentedRecordWriter"
      - target: "ScreenRecordWriter"
      - target: "RecoreonCommon"
      - package: "FFmpegKit"
    settings:
      SWIFT_OBJC_BRIDGING_HEADER: "RecoreonBroadcastUploadExtension/RecoreonBroadcastUploadExtension-Bridging-Header.h"
      PRODUCT_BUNDLE_IDENTIFIER: "com.github.umireon.Recoreon.RecoreonBroadcastUploadExtension"
      SKIP_INSTALL: true
    info:
      path: "RecoreonBroadcastUploadExtension/Info.plist"
      properties:
        CFBundleDisplayName: "Recoreon"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSCameraUsageDescription: "This app do not use a camera."
        NSExtension:
          NSExtensionPointIdentifier: "com.apple.broadcast-services-upload"
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).SampleHandler"
          RPBroadcastProcessMode: "RPBroadcastProcessModeSampleBuffer"
    entitlements:
      path: "RecoreonBroadcastUploadExtension/RecoreonBroadcastUploadExtension.entitlements"
      properties:
        com.apple.security.application-groups:
          - "group.com.github.umireon.Recoreon"

  Recoreon:
    type: "application"
    platform: "iOS"
    sources:
      - "Recoreon"
    settings:
      DEVELOPMENT_ASSET_PATHS: '"Recoreon/Preview Content"'
      ENABLE_PREVIEWS: true
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"
      SWIFT_OBJC_BRIDGING_HEADER: "Recoreon/Recoreon-Bridging-Header.h"
    dependencies:
      - target: "RecoreonCommon"
      - target: "RecoreonBroadcastUploadExtension"
      - package: "FFmpegKit"
    settings:
      GCC_GENERATE_TEST_COVERAGE_FILES: true
      GCC_INSTRUMENT_PROGRAM_FLOW_ARCS: true
      SWIFT_EMIT_LOC_STRINGS: true
    info:
      path: "Recoreon/Info.plist"
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        ITSAppUsesNonExemptEncryption: false
        LSRequiresIPhoneOS: true
        NSCameraUsageDescription: "This app do not use a camera."
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations~ipad:
          - "UIInterfaceOrientationPortrait"
          - "UIInterfaceOrientationPortraitUpsideDown"
          - "UIInterfaceOrientationLandscapeLeft"
          - "UIInterfaceOrientationLandscapeRight"
        UISupportedInterfaceOrientations~iphone:
          - "UIInterfaceOrientationPortrait"
          - "UIInterfaceOrientationLandscapeLeft"
          - "UIInterfaceOrientationLandscapeRight"
    entitlements:
      path: "Recoreon/Recoreon.entitlements"
      properties:
        com.apple.security.application-groups:
          - "group.com.github.umireon.Recoreon"

  RecoreonTests:
    type: "bundle.unit-test"
    platform: "iOS"
    sources:
      - "RecoreonTests"
    dependencies:
      - target: "Recoreon"
      - target: "ScreenRecordWriter"
      - package: "FFmpegKit"
    settings:
      SWIFT_OBJC_BRIDGING_HEADER: "RecoreonTests/RecoreonTests-Bridging-Header.h"
    info:
      path: "RecoreonTests/Info.plist"
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"

  RecoreonUITests:
    type: "bundle.ui-testing"
    platform: "iOS"
    sources:
      - "RecoreonUITests"
    dependencies:
      - target: "Recoreon"
    info:
      path: "RecoreonUITests/Info.plist"
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"

schemes:
  Recoreon:
    build:
      targets:
        Recoreon: "all"
        RecoreonTests:
          - "test"
        RecoreonUITests:
          - "test"
    test:
      testPlans:
        - path: "RecoreonTests.xctestplan"
          defaultPlan: true
        - path: "RecoreonUITests.xctestplan"
        - path: "FragmentedRecordWriterTests.xctestplan"

  RecoreonBroadcastUploadExtension:
    build:
      targets:
        RecoreonBroadcastUploadExtension: "all"
        Recoreon: "none"
