---
name: "clang-format"

"on":
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ClangFormat:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install clang-format"
        run: "sudo apt-get -y install --no-install-recommends clang-format"

      - name: "Run clang-format"
        run: ".github/scripts/check-clang-format.sh"
