---
name: "shellcheck"

"on":
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  Shellcheck:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install zsh"
        run: "sudo apt-get -y install --no-install-recommends zsh"

      - name: "Run shellcheck"
        run: ".github/scripts/check-shellcheck.sh"
