---
name: "sort-Xcode-project-file"

"on":
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  SortXcodeProjectFile:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Sort xcodeproj"
        run: ".github/scripts/sort-Xcode-project-file Recoreon.xcodeproj"

      - name: "Check if files are changed"
        run: "git diff --quiet Recoreon.xcodeproj"
