---
name: "swiftlint"

"on":
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  SwiftLint:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Swift"
        run: "sudo apt-get -y install --no-install-recommends swift"

      # yamllint disable rule:line-length
      - name: "Install SwiftLint"
        shell: bash
        run: |
          curl -fsSLO https://github.com/realm/SwiftLint/releases/download/0.53.0/swiftlint_linux.zip
          mkdir -p swiftlint_linux
          unzip swiftlint_linux.zip -d swiftlint_linux
          echo "${{ github.workspace }}/swiftlint_linux" >> "$GITHUB_PATH"
      # yamllint enable rule:line-length

      - name: "Run SwiftLint"
        run: "swiftlint"
