name: "swift-format"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  SwiftFormat:
    runs-on: "macos-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      
      - name: "Run swift-format"
        run: "swift-format lint --recursive Recoreon RecoreonBroadcastUploadExtension RecoreonBroadcastUploadExtensionSetupUI RecoreonTests RecoreonUITests"
