---
name: "yamllint"

"on":
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  Yamllint:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install yamllint"
        run: "sudo apt-get -y install --no-install-recommends yamllint"

      - name: "Run swift-format"
        run: "yamllint .github"
